# Sample config defaults file (this settings are set to be used with the PPO algorithm: to be changed to make it suitable for the SAC algorithm):
program: main.py
method: grid
metric:
  name: best_score
  goal: maximize
parameters:
  lr_ppo:
    values: [0.1, 0.4]
  batch_size:
    values: [16, 32]
  epoch_duration:
    values: [20, 21]
early_terminate:
  type: hyperband
  max_iter: 2
  s: 2
